spring:
  application:
    name: AesopServer
  threads:
    virtual:
      enabled: true

server:
  port: 8870

aesop:
  brain:
    aesop-root: "C:\\Users\\matt8\\aesop"
    conductor-root: "C:\\Users\\matt8\\conductor3"
  db-path: "C:\\Users\\matt8\\aesop\\state\\tracker_events.db"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    app:
      encoding: "@project.build.sourceEncoding@"
      java:
        source: "@java.version@"
        target: "@java.version@"
